#!/usr/bin/env bash
# Transfers a file to a remote server using scp with specific parameters

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning variables for readability
FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Transfer the file
# -i: specifies the private key
# -o StrictHostKeyChecking=no: disables the authenticity prompt for new hosts
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME"@"$IP":~/
