#!/usr/bin/env bash
# Transfers a file from the client to the server home directory disabling strict host key checking

if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$IP:~/"
